### ISSUE TITLE
Menu extras are the wrong color

### ISSUE THREAD

**Issue by ljharb** [tylerhall/SurtainlyNot#2]
Thanks for this tool, I abhor the transparent menu bar (but require a transparent Dock).

However, when I use this tool, all the menu extras end up white-on-white. Perhaps you're using dark mode and haven't tried it in the default "light" mode? Happy to provide screenshots if it would help.

**Comment by tylerhall** [comment]
Hey, @ljharb. No, I never run macOS in dark mode 🤔 Not sure what the bug is.

That said, I'm actually not even using SurtainlyNot any longer. I started using Boring Old Menu Bar, which solves the same problem but is much more reliable - and I'm happy to support another indie developer to handle it for me :) Take a look at the app here...

https://www.publicspace.net/BoringOldMenuBar/

**Comment by ljharb** [comment]
ah ok, thanks! I’ll try that :-)
